"""TranscriptEvent model representing recognized speech output."""

from dataclasses import dataclass
from typing import Final

# Language identifier constants
LANG_MARATHI: Final[str] = "mr"
LANG_HINDI: Final[str] = "hi"
LANG_ENGLISH: Final[str] = "en"
LANG_UNKNOWN: Final[str] = "unknown"


@dataclass(frozen=True)
class TranscriptEvent:
    """Immutable event payload generated by Speech Recognition engine.

    Attributes:
        text: Transcribed text content.
        language: Auto-detected ISO 639-1 language code ('mr', 'hi', 'en').
        start_time: Start timestamp of speech window in seconds.
        end_time: End timestamp of speech window in seconds.
        confidence: Normalized confidence or log probability score (0.0 to 1.0).
        is_final: True if segment transcription is complete; False if streaming partial.
        sequence_number: Monotonically increasing transcript segment index.
    """

    text: str
    language: str
    start_time: float
    end_time: float
    confidence: float
    is_final: bool
    sequence_number: int

    @property
    def duration_sec(self) -> float:
        """Compute duration of transcribed speech segment in seconds."""
        return max(0.0, float(self.end_time - self.start_time))

    @property
    def language_label(self) -> str:
        """Return human-readable language display label."""
        labels = {
            LANG_MARATHI: "Marathi",
            LANG_HINDI: "Hindi",
            LANG_ENGLISH: "English",
        }
        return labels.get(self.language.lower(), self.language.upper())
